# Makefile for CNSS platform driver

ccflags-y += -I$(src)
obj-$(CONFIG_CNSS_PCI)	+= cnss_pci.o
obj-$(CONFIG_CNSS_SDIO)	+= cnss_sdio.o
obj-$(CONFIG_CNSS)	+= cnss_common.o
obj-$(CONFIG_CNSS_LOGGER)	+= logger/
