#
# Makefile for IIO Health sensors
#

# When adding new entries keep the list in alphabetical order

ccflags-y += -I$(src)
obj-$(CONFIG_AFE4403)		+= afe4403.o
obj-$(CONFIG_AFE4404)		+= afe4404.o
obj-$(CONFIG_MAX30100)		+= max30100.o
