#
# Makefile for the tablet drivers
#


ccflags-y += -I$(src)
obj-$(CONFIG_TABLET_USB_ACECAD)	+= acecad.o
obj-$(CONFIG_TABLET_USB_AIPTEK)	+= aiptek.o
obj-$(CONFIG_TABLET_USB_GTCO)	+= gtco.o
obj-$(CONFIG_TABLET_USB_HANWANG) += hanwang.o
obj-$(CONFIG_TABLET_USB_KBTAB)	+= kbtab.o
obj-$(CONFIG_TABLET_USB_PEGASUS) += pegasus_notetaker.o
obj-$(CONFIG_TABLET_SERIAL_WACOM4) += wacom_serial4.o
