#
# Makefile for Invensense icm20602 device.
#

ccflags-y += -I$(src)
obj-$(CONFIG_INV_ICM20602_IIO) += inv-icm20602.o
inv-icm20602-objs := inv_icm20602_core.o inv_icm20602_ring.o inv_icm20602_trigger.o inv_icm20602_bsp.o
